name: Deploy Firebase Rules

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "firestore.rules.*"
      - "storage.rules"
      - "firestore.indexes.json"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (dev/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy-firebase-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment based on branch or input
        id: set-environment
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          else
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy Firebase Rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [[ "${{ env.ENVIRONMENT }}" == "prod" ]]; then
            echo "Deploying to PRODUCTION environment"
            firebase use prod --token "$FIREBASE_TOKEN"
            firebase deploy --only firestore:rules,storage:rules -c firebase.prod.json --token "$FIREBASE_TOKEN"
          else
            echo "Deploying to DEVELOPMENT environment"
            firebase use dev --token "$FIREBASE_TOKEN"
            firebase deploy --only firestore:rules,storage:rules -c firebase.dev.json --token "$FIREBASE_TOKEN"
          fi
